---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - test/dummy/**/*
    - gemfiles/**/*
    - vendor/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*
