---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - test/dummy/**/*
    - gemfiles/**/*
    - vendor/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/OpenStructUse:
  Exclude:
    - test/**/*
